### ISSUE TITLE
iPhone X 适配（支付宝容器内）

### ISSUE THREAD

**Issue by xinconan** [xinconan/blog#12]
H5页面在支付宝容器中，如果设置了沉浸式，是会存在安全区域问题的。
那么如何进行适配呢？
1. 设置 `viewport-fit=cover`
```html
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
```
2. 设置css样式：

```scss
// iPhone X适配
@media only screen and (device-width: 375Px) and (device-height: 812Px) and (-webkit-device-pixel-ratio: 3) {
  .mask-wrapper{
      margin-top: calc(-530px - constant(safe-area-inset-top));
      margin-top: calc(-530px - env(safe-area-inset-top));
   }
}
```
在实际开发中发现，`safe-area-inset-top` 并不只在iPhone X中存在，在iPhone 6等其他高版本iOS中也有，而且值不是0（支付宝容器中是这样的）！！所以精确匹配可以使用上述的媒体查询方法。
