### ISSUE TITLE
css实现水平垂直居中的方法

### ISSUE THREAD

**Issue by xinconan** [xinconan/blog#2]
# 固定宽高的情况
``` html
<div class="father">
    <div class="son"></div>
</div>
```
``` css
.father {
    width: 300px;
    height: 150px;
    background-color: #f0f3f9;
    position: relative;
}
.son {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    width: 200px;
    height: 100px;
    background-color: #cd0000;
    margin: auto;
}
```
# 不固定宽高
## flexbox + margin
``` html
<div class="father">
    <div class="son"></div>
</div>
```
```css
.father{
  display: flex;
}
.son{
  marin: auto;
}
```
