### ISSUE TITLE
解决图片下方的空白幽灵节点

### ISSUE THREAD

**Issue by xinconan** [xinconan/blog#3]
1. 图片块状化
```css
.img{
  display: block;
}
```
2. 父层容器 `font-size: 0;`
3. 父层容器 `line-height: 0;`
4. 图片设置 `vertical-align` 为其他属性（top、middle、bottom）

> 参考：css世界
