### ISSUE TITLE
css隐藏滚动条

### ISSUE THREAD

**Issue by xinconan** [xinconan/blog#5]
对于Chrome、Safari和Opera，可以使用如下CSS：
```css
.container::-webkit-scrollbar {
  display: none;
}
```
IE或 Edge 可以使用：
```css
.container {
  -ms-overflow-style: none;
}
```
至于 Firefox，无法隐藏滚动条！
